### ISSUE TITLE
[1.x] Add stub .travis.yml

### ISSUE THREAD

**Issue by mbabker** [joomla/coding-standards#165]
To turn on Travis-CI for the repo and not have it groan about missing config or things like that, we'll need a stub Travis configuration file on the master/1.x branch.  https://github.com/joomla/joomla-cms/blob/2.5.28/.travis.yml is what we used for the CMS on the 2.5 branch.

**Comment by photodude** [comment]
how about 
```yml
sudo: false
dist: trusty
language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
```
